### ISSUE TITLE
GFAffix strips header information

### ISSUE THREAD

**Issue by glennhickey** [marschall-lab/GFAffix#7]
In vg we're using these "RS" GFA header tags to distinguish between reference and haplotype paths in W-lines.  But this information is getting lost in GFAffix which apparently just writes `H VG:Z:1.0` in the output no matter what.  This is not an urgent issue as it's so easy to work around, but it would be nice if GFAffix would be updated to preserve the input H line as is.

**Comment by danydoerr** [comment]
That makes sense--will be fixed in the next release.
